apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "replizieren.fullname" . }}-manager-rolebinding
  labels:
    {{- include "replizieren.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "replizieren.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "replizieren.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
